AssetTrack/Models/Asset.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AssetTrack.Models
{
    public class Asset
    {
        public int Id { get; set; }

        public DateTime Date { get; set; }
        public string Location { get; set; }

        [DisplayName("Part Type")]
        public string PartType { get; set; }

        public string MSF { get; set; }

        [DisplayName("Part Number")]
        public string PartNumber { get; set; }

        [DisplayName("Serial Number")]
        public string SerialNumber { get; set; }

        [DisplayName("Task Number")]
        public string TaskNumber { get; set; }

        public string Notes { get; set; }
        public string User { get; set; }
       
        
    }
}

AssetTrack/Models/ErrorViewModel.cs
namespace AssetTrack.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AssetTrack/Controllers/AssetsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AssetTrack.Data;
using AssetTrack.Models;
using Microsoft.AspNetCore.Authorization;

namespace AssetTrack.Controllers
{

    public class AssetsController : Controller
    {
        private readonly AssetTrackContext _context;

        public AssetsController(AssetTrackContext context)
        {
            _context = context;
        }


        // Requires user auth to proceed with view
        [Authorize]
        // GET: Assets/Index/
        public async Task<IActionResult> Index()
        {
            return View(await _context.Asset.ToListAsync());
        }

        [Authorize]
        // GET: Assets/Details/
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var asset = await _context.Asset
                .FirstOrDefaultAsync(m => m.Id == id);
            if (asset == null)
            {
                return NotFound();
            }

            return View(asset);
        }

        // Requires user auth to proceed with view
        [Authorize]
        // GET: Assets/Create/
        public IActionResult Create()
        {
            return View();
        }

        // POST: Assets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Date,Location,PartType,MSF,PartNumber,SerialNumber,TaskNumber,Notes,User")] Asset asset)
        {
            if (ModelState.IsValid)
            {
                _context.Add(asset);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(asset);
        }
       
        
        [Authorize]
        // GET: Assets/Edit/
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var asset = await _context.Asset.FindAsync(id);
            if (asset == null)
            {
                return NotFound();
            }
            return View(asset);
        }

        // POST: Assets/Edit/
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Date,Location,PartType,MSF,PartNumber,SerialNumber,TaskNumber,Notes,User")] Asset asset)
        {
            if (id != asset.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(asset);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AssetExists(asset.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(asset);
        }

        [Authorize]
        // GET: Assets/Delete/
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var asset = await _context.Asset
                .FirstOrDefaultAsync(m => m.Id == id);
            if (asset == null)
            {
                return NotFound();
            }

            return View(asset);
        }

        [Authorize]
        // POST: Assets/Delete/
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var asset = await _context.Asset.FindAsync(id);
            _context.Asset.Remove(asset);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AssetExists(int id)
        {
            return _context.Asset.Any(e => e.Id == id);
        }

    }
}

AssetTrack/Controllers/HomeController.cs
using AssetTrack.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AssetTrack.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
       
    }
}

AssetTrack/Controllers/SearchController.cs
using AssetTrack.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AssetTrack.Controllers
{
    public class SearchController : Controller
    {
        private readonly AssetTrackContext _context;

        public SearchController(AssetTrackContext context)
        {
            _context = context;
        }


        [Authorize]
        [HttpPost]
        public string Index(string searchString, bool notUsed)
        {
            return "From [HttpPost]Index: filter on " + searchString;
        }


        [Authorize]
        // GET: Asset
        public async Task<IActionResult> Index(string searchString)
        {
            //Using LINQ to create query 
            var assets = from t in _context.Asset
                         select t;


            if (!String.IsNullOrWhiteSpace(searchString))
            {
                assets = assets.Where(i => i.Location!.Contains(searchString) ||

                i.MSF!.Contains(searchString) ||
                i.Date!.ToString().Contains(searchString) ||
                i.User!.Contains(searchString) ||
                i.Notes!.Contains(searchString) ||
                i.PartNumber!.Contains(searchString) ||
                i.PartType!.Contains(searchString) ||
                i.SerialNumber!.Contains(searchString) ||
                i.TaskNumber!.Contains(searchString

                ));
            }


            return View(await assets.ToListAsync());
        }

    }
}

AssetTrack/Views/Assets/Create.cshtml
@model AssetTrack.Models.Asset

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>
<br />
<br />



<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <br />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">   
                <input type="hidden" asp-for="Date" value='@DateTime.Now' class="form-control" />
                <span asp-validation-for="Date"class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MSF" class="control-label"></label>
                <input asp-for="MSF" class="form-control" />
                <span asp-validation-for="MSF" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PartType" class="control-label"></label>
                <input asp-for="PartType" class="form-control" />
                <span asp-validation-for="PartType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PartNumber" class="control-label"></label>
                <input asp-for="PartNumber" class="form-control" />
                <span asp-validation-for="PartNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SerialNumber" class="control-label"></label>
                <input asp-for="SerialNumber" class="form-control" />
                <span asp-validation-for="SerialNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TaskNumber" class="control-label"></label>
                <input asp-for="TaskNumber" class="form-control" />
                <span asp-validation-for="TaskNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">              
                <input type="hidden" asp-for="User" value ='@User.Identity.Name' class="form-control" />
                <span asp-validation-for="User" class="text-danger"></span>
            </div>
            <div class="form-group">
                <br />
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AssetTrack/Views/Assets/Delete.cshtml
@model AssetTrack.Models.Asset

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>
<br />
<br />


<h3>Are you sure you want to delete this record?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MSF)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MSF)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PartType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PartType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PartNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PartNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SerialNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SerialNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TaskNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TaskNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Notes)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AssetTrack/Views/Assets/Details.cshtml
@model AssetTrack.Models.Asset

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
<br />
<br />


<div>
    <h4>Asset</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MSF)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MSF)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PartType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PartType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PartNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PartNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SerialNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SerialNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TaskNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TaskNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Notes)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AssetTrack/Views/Assets/Edit.cshtml
@model AssetTrack.Models.Asset

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>
<br />
<br />


<h4>Asset</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                
                <input type="hidden" asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>          
            <div class="form-group">
                <label asp-for="PartType" class="control-label"></label>
                <input asp-for="PartType" class="form-control" />
                <span asp-validation-for="PartType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MSF" class="control-label"></label>
                <input asp-for="MSF" class="form-control" />
                <span asp-validation-for="MSF" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PartNumber" class="control-label"></label>
                <input asp-for="PartNumber" class="form-control" />
                <span asp-validation-for="PartNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SerialNumber" class="control-label"></label>
                <input asp-for="SerialNumber" class="form-control" />
                <span asp-validation-for="SerialNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TaskNumber" class="control-label"></label>
                <input asp-for="TaskNumber" class="form-control" />
                <span asp-validation-for="TaskNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AssetTrack/Views/Assets/Index.cshtml
@model IEnumerable<AssetTrack.Models.Asset>

@{
    ViewData["Title"] = "Inventory Index";
}

<h1>Inventory Index</h1>
<br />
<br />


<p>
    <a asp-action="Create"><input class="btn btn-primary" value="Create New" ></a>
</p>
<form asp-controller="Assets" asp-action="Index" method="get"></form>
<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MSF)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PartType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PartNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SerialNumber)
            </th>
              <th>
                @Html.DisplayNameFor(model => model.TaskNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Notes)               
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr class="table-Secondary">
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MSF)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PartType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PartNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SerialNumber)
            </td>
             <td>
                @Html.DisplayFor(modelItem => item.TaskNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Notes)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

AssetTrack/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center"> 
    <br />
    <br />

    <h1 class="text-4">Welcome to AssetTrack!</h1>

    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />

   <h4 class="text-4">Please use the guide below to learn how to use and navigate around the app.</h4>
</div>
    
    
    
<br />

<br />


<div class="text-center">

<img   src="~/img/Register.png" width=80% height=80% >
<br />

<img  src="~/img/Login.png" width=80% height=80% >
<br />

<img  src="~/img/Inventory.png" width=80% height=80% >
<br />

<img  src="~/img/Create.png"  width=80% height=80% >
<br />

<img  src="~/img/Details.png" width=80% height=80% >
<br />

<img src="~/img/Search.png" width=80% height=80% >
<br />

<img  src="~/img/User settings.png" width=80% height=80% >
<br />

<br />
</div>
    

AssetTrack/Views/Search/Index.cshtml
@model IEnumerable<AssetTrack.Models.Asset>

@{
    ViewData["Title"] = "Search Records";
}

<h1>Search Records</h1>
<br />
<br />


<form asp-controller="Search" asp-action="Index" method="get">
    <p>
  <input type="text" name="SearchString" />
        <input class="btn btn-success"   type="submit" value="Filter" />
    </p>
</form>

<br />


<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MSF)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PartType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PartNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SerialNumber)
            </th>
              <th>
               @Html.DisplayNameFor(model => model.TaskNumber)
            </th>
            <th>
               @Html.DisplayNameFor(model => model.Notes)               
            </th>
            <th>
               @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
               @Html.DisplayNameFor(model => model.User)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr class="table-Secondary">        
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MSF)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PartType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PartNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SerialNumber)
            </td>
             <td>
                @Html.DisplayFor(modelItem => item.TaskNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Notes)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User)
            </td>

        </tr>
}
    </tbody>
</table>

AssetTrack/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AssetTrack</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AssetTrack.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand"><b>AssetTrack</b></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Assets" asp-action="Index">Inventory</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Search" asp-action="Index">Search</a>
                        </li>
                        <li class="nav-item">
                         <a  class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">User settings</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AssetTrack 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>